# docker/docker-compose.yml
version: '3'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../:/app
    ports:
      - "5000:5000"
    environment:
      - PYTHONPATH=/app
      - DEBUG=1
    command: python -m my_library

  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../:/app
    ports:
      - "5555:5555"
    environment:
      - PYTHONPATH=/app
    command: uvicorn api:app --host 0.0.0.0 --port 5555

  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../:/app
    ports:
      - "7860:7860"
    environment:
      - PYTHONPATH=/app
      - API_URL=http://api:5555/crop-image/
    command: python web.py
    depends_on:
      - api